// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/types/supabase';

const SUPABASE_URL = "https://weuczjmzumxigfobwbod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndldWN6am16dW14aWdmb2J3Ym9kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNDM0NzYsImV4cCI6MjA2NzkxOTQ3Nn0.U1ojWYeyWdoTIpzWe6EWZrxPXwOQ50i3Ks2LdkdN-5c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});